// <auto-generated/>
#pragma warning disable CS0618
using ApiServiceSDK.Patients.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiServiceSDK.Patients
{
    /// <summary>
    /// Builds and executes requests for operations under \patients
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PatientsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ApiServiceSDK.patients.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ApiServiceSDK.Patients.Item.WithPatientItemRequestBuilder"/></returns>
        public global::ApiServiceSDK.Patients.Item.WithPatientItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("patientId", position);
                return new global::ApiServiceSDK.Patients.Item.WithPatientItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiServiceSDK.Patients.PatientsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PatientsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/patients", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiServiceSDK.Patients.PatientsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PatientsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/patients", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
